name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Make Test
      id: make-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Make Test
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAKE-TEST_RESULTS: "${{steps.make-test.outputs.result}}"
      with:
        runners: make-test
